[package]
name = "x11-pbcopy-pbpaste"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pbcopy"
path = "./src/pbcopy.rs"

[[bin]]
name = "pbpaste"
path = "./src/pbpaste.rs"

[dependencies]
nix = "0.23.1"
x11-clipboard = "0.5.3"
